SELECT LICENSENUMBER, P_NAME, (AGE / (GOALS / SHOTPERCENT)) AS EFFECTIVENESS
FROM PLAYERS
WHERE SHOTPERCENT != 0
ORDER BY EFFECTIVENESS DESC
FETCH FIRST 5 ROWS ONLY;

SELECT * 
FROM MANAGERS 
WHERE WINPERCENT != 0
ORDER BY WINPERCENT DESC
FETCH FIRST 5 ROWS ONLY;

SELECT * 
FROM COACHES
WHERE WINPERCENT != 0
ORDER BY WINPERCENT DESC
FETCH FIRST 5 ROWS ONLY;

SELECT PLAYER, COUNT(PLAYER), 
FROM VIOLATIONS
GROUP BY PLAYER
ORDER BY COUNT(PLAYER) DESC
FETCH FIRST 5 ROWS ONLY;

SELECT PLAYERS.LICENSENUMBER, PLAYERS.P_NAME, PLAYER_CONTRACTS.CONTRACTID, (PLAYER_CONTRACTS.SALARY / (PLAYERS.GOALS + 0.5*PLAYERS.ASSISTS)) AS ROI
FROM PLAYERS INNER JOIN PLAYER_CONTRACTS 
ON PLAYER_CONTRACTS.PERSON = PLAYERS.LICENSENUMBER
ORDER BY ROI DESC
FETCH FIRST 5 ROWS ONLY;

SELECT COACHES.LICENSEID, COACHES.FIRST_NAME, COACHES.LAST_NAME, COACH_CONTRACTS.CONTRACTID, (COACH_CONTRACTS.SALARY / COACHES.WINPERCENT) AS ROI
FROM COACHES INNER JOIN COACH_CONTRACTS 
ON COACH_CONTRACTS.PERSON = COACHES.LICENSEID 
WHERE COACHES.WINPERCENT != 0
ORDER BY ROI DESC
FETCH FIRST 5 ROWS ONLY;

SELECT MANAGERS.LICENSEID, MANAGERS.FIRST_NAME, MANAGERS.LAST_NAME, MANAGER_CONTRACTS.CONTRACTID, (MANAGER_CONTRACTS.SALARY / MANAGERS.WINPERCENT) AS ROI
FROM MANAGERS INNER JOIN MANAGER_CONTRACTS 
ON MANAGER_CONTRACTS.PERSON = MANAGERS.LICENSEID 
WHERE MANAGERS.WINPERCENT != 0
ORDER BY ROI DESC
FETCH FIRST 5 ROWS ONLY;

WITH RELIABILITY AS 
(SELECT AVG(GOALS + 0.5*ASSISTS) AS MEAN, STDDEV(GOALS + 0.5*ASSISTS) AS STD FROM PLAYERS)
SELECT *, ((GOALS + 0.5*ASSISTS - RELIABILITY.MEAN) / RELIABILITY.STD) AS ZSCORE
FROM PLAYERS
ORDER BY ZSCORE DESC
FETCH FIRST 5 ROWS ONLY;

WITH TEAM-FIELD AS
(SELECT UNID, HOME FROM TEAMS) AS FIELDS
SELECT *, COUNT(WINNINGTEAM) AS COUNTWIN
FROM GAMES
WHERE (GAMES.WINNINGTEAM = FIELDS.UNID && GAMES.GFIELD = FIELDS.HOME)
ORDER BY COUNTWIN DESC
FETCH FIRST 5 ROWS ONLY;

